linz/step-ag-grid

src/components/gridForm/GridFormPopoutMenu.tsx, src/stories/components/GridReadOnly.stories.tsx
Sometimes context menus have options that should only show under certain conditions. Adding a little flag to the MenuOption interface means the code in the app is tidier in these scenarios.
Post merge
**perf**: A code change that improves …
=> feat: allow menu options to be hidden

index.ts
Add export for GridSubComponentTextArea at root of package
Post merge
**test**: Adding missing tests or correcting …
=> fix: export GridSubComponentTextArea from root

src/components/gridForm/GridFormMultiSelect.tsx, src/stories/components/GridPopoutEditMultiSelect.stories.tsx
* Update the the save function to return a map of values. 
* provide an optional parameter to  provide the initial selected values of the multiselect
Post merge
**fix**: A …
=> fix: pass values record back to save callback

src/components/gridForm/GridFormDropDown.tsx, src/stories/components/GridPopoutEditDropDown.stories.tsx
A few of the existing drop down editors contain headers in the list of options. This PR allows them to be added in a similar fashion to MenuSeparators
Post merge
**refactor**: A code …
=> Ability to add headers to drop downs

.github/dependabot.yml, .github/workflows/chromatic.yml, .github/workflows/deploy-storybook.yml, README.md, package.json, src/react-menu3/components/ControlledMenu.tsx, src/react-menu3/components/FocusableItem.tsx, src/react-menu3/components/MenuGroup.tsx, src/react-menu3/components/MenuItem.tsx, src/react-menu3/components/MenuList.tsx, src/react-menu3/components/MenuRadioGroup.tsx, src/react-menu3/components/SubMenu.tsx, src/react-menu3/contexts/EventHandlersContext.ts, src/react-menu3/contexts/HoverItemContext.ts, src/react-menu3/contexts/ItemSettingsContext.ts, src/react-menu3/contexts/MenuListContext.ts, src/react-menu3/contexts/MenuListItemContext.ts, src/react-menu3/contexts/RadioGroupContext.ts, src/react-menu3/contexts/SettingsContext.ts, src/react-menu3/hooks/useItemState.ts, src/react-menu3/utils/constants.ts, src/react-menu3/utils/withHovering.tsx
fix: Move contexts to own files, use Lui workflows, make mouse down trigger save
Post merge
**test**: Adding missing …
=> fix: Move contexts to own files, use Lui workflows, make mouse down trigger save

package.json, src/components/gridPopoverEdit/GridPopoverMenu.tsx, src/lui/ActionButton.tsx, src/stories/components/ActionButton.stories.tsx, src/stories/grid/GridPopoutEditGenericTextArea.stories.tsx, src/stories/grid/GridPopoutEditMultiSelect.stories.tsx, src/stories/grid/GridReadOnly.stories.tsx
fix: action button manages own state, and now external state setter
Post merge
**test**: Adding missing tests or …
=> fix: action button manages own state

src/contexts/GridContextProvider.tsx
fix: sizeColumnsToFit errors in test
In test documents have zero size which causes warnings.  This checks doc clientWidth before calling sizeColumnsToFit.
=> fix: sizeColumnsToFit errors in test

src/components/GridSubComponentTextArea.tsx, src/components/gridForm/GridFormPopoverMenu.tsx, src/components/gridForm/GridFormTextInput.tsx, src/lui/TextAreaInput.tsx, src/lui/TextInputFormatted.tsx, src/stories/grid/GridPopoutEditGenericTextArea.stories.tsx, src/stories/grid/GridReadOnly.stories.tsx
* Action handlers now return the menu option clicked plus any subcomponent values
* Action handlers no longer return true/false, as it wasn't used I removed it.
* Mouse over input will trigger input focus
=> feat: subcomponents-in-popover-menus, focus inputs on mouseover

src/components/GridCell.tsx, src/components/GridPopoverHook.tsx, src/components/gridForm/GridFormDropDown.tsx, src/components/gridForm/GridFormEditBearing.tsx, src/components/gridForm/GridFormMessage.tsx, src/components/gridForm/GridFormMultiSelect.tsx, src/components/gridForm/GridFormPopoverMenu.tsx, src/components/gridForm/GridFormSubComponentTextInput.tsx, src/components/gridForm/GridFormTextArea.tsx, src/components/gridForm/GridFormTextInput.tsx, src/contexts/GridPopoverContext.tsx, src/contexts/GridPopoverContextProvider.tsx, src/react-menu3/components/MenuList.tsx, src/react-menu3/contexts/SettingsContext.ts, src/stories/grid/FormTest.tsx, src/stories/grid/GridPopoutEditMultiSelect.stories.tsx, src/stories/grid/GridReadOnly.stories.tsx
Old style:
```
const props = _props as GridFormPopoutDropDownProps<RowType, ValueType> & CellParams<RowType>;
const { selectedRows, field, updateValue } = props;
```
Has changed to:
```
const { selectedRows, field, updateValue } = useContext(GridPopoverContext);
```
=> BREAKING CHANGE: forms now get values from context

src/components/gridForm/GridFormSubComponentTextArea.tsx, src/components/gridForm/GridFormSubComponentTextInput.tsx, src/components/gridForm/GridFormTextArea.tsx, src/components/gridForm/GridFormTextInput.tsx
fix: prevent tab out of div in genericinput and textarea
=> fix: prevent tab out of div in genericinput and textarea

src/components/GridCell.tsx, src/components/gridForm/GridFormDropDown.tsx, src/styles/GridFormDropDown.scss
fix: suppress unwanted grid keyboard events, [Empty] is now _No options_ in dropdown
=> fix: suppress unwanted grid keyboard events, [Empty] is now _No options_ in dropdown

src/stories/grid/GridPopoutBearing.stories.tsx, src/utils/bearing.ts
Show `+1 00' 00"` instead `+1 00'` in Bearing correction
Post merge
**test**: Adding missing tests or correcting …
=> fix: Use original Bearing correction format

src/utils/bearing.ts
The validation message for the default regex check for bearings referred to positive numbers exclusively. In some situations negative bearings are allowed and the regex actually allows for this. The message has been tweaked so it doesn't refer to positive numbers only.
Post merge …
=> fix: bearing regex validation message does not refer to positive numbers

src/components/Grid.tsx, src/components/gridHeader/GridHeaderSelect.tsx, src/contexts/GridContextProvider.tsx
Otherwise tests start editing before focus can run, and setting focus cancels edit.
=> fix: dont focus cell if currently editing

src/utils/testUtil.ts
A few of the existing tests validate the menu options for an editor by passing in an array of values. This PR adds a function to do this with the step-ag-grid to replace the existing functions that use the old grid querying code.
Post merge
**fix**: A bug …
=> feat: added test function for validating menu options

src/components/Grid.tsx, src/stories/grid/GridNonEditableRow.stories.tsx
The editable prop on the defaultColumn object was not being used to change a cells editable state. This PR fixes this and adds a storybook for test to cover it.
Post merge
**refactor**: A …
=> fix: default column prop not being used

src/components/gridPopoverEdit/GridPopoverMenu.tsx
If min width is not set action menu icon dissapears.
=> fix: minwidth on action menu

src/components/gridForm/GridFormTextInput.tsx
Width was only applying to container, not the text input.
=> fix: text input width not applied correctly

src/components/Grid.tsx, src/components/gridForm/GridFormPopoverMenu.tsx, src/stories/grid/GridReadOnly.stories.tsx, src/stories/grid/gridForm/GridFormMultiSelect.stories.tsx
fix: popup menu not closing on action after invalid subcomponent
fix: cell edit stop steals focus from popup dialog
=> fix: popup menu not closing on action after invalid subcomponent, cell edit stop steals focus

src/components/Grid.tsx, src/components/GridCell.tsx, src/components/gridForm/GridFormDropDown.tsx, src/components/gridPopoverEdit/GridPopoverMenu.tsx, src/stories/grid/GridNonEditableRow.stories.tsx
feat: Use inheritance to apply editable states from Grid.readOnly -> defaultColumnDef.editable -> columnDef.editable
fix: When you click away from a dropdown the last hovered item is selected, but it shouldn't as it's not longer hovered.
=> fix: editable inheritance, dropdown incorrectly selecting on click away

src/components/Grid.tsx, src/stories/grid/GridPopoutBearing.stories.tsx
fix: grid readonly flag is inverted
=> fix: grid readonly flag is inverted

src/styles/Grid.scss
Slight padding change such that headers are visiually the same
=> fix: make aggrid 28 header same as 27

package-lock.json, package.json, src/components/Grid.tsx, src/react-menu3/components/ControlledMenu.tsx, src/styles/Grid.scss, src/utils/textValidator.test.ts, src/utils/textValidator.ts
Aggrid 28 breaks tests due to a jsdom bug focusin event bug, so this reverts to v27.
Also fix enter to save not working in multiselect.
BREAKING CHANGE: Revert to v27 aggrid
=> BREAKING CHANGE: Revert to v27 aggrid

src/components/Grid.tsx, src/components/GridFilter.ts, src/components/GridWrapper.tsx, src/components/gridFilter/GridFilterQuick.tsx, src/components/gridFilter/GridFilters.tsx, src/contexts/GridContext.tsx, src/contexts/GridContextProvider.tsx, src/stories/grid/GridPopoverEditBearing.stories.tsx, src/stories/grid/GridReadOnly.stories.tsx, src/styles/Grid.scss
QuickFilter moved out of grid and is now it's own component.
Ability to add external filters added.
```
<GridContextProvider>
<GridWrapper>
<GridFilters>
<GridFilterQuick quickFilterPlaceholder={"Custom placeholder..."} />
<div>
Custom filter: Age less than:
<GridFilterLessThan field={"age"} />
</div>
</GridFilters>
<Grid
{...props}
selectable={true}
externalSelectedItems={externalSelectedItems}
setExternalSelectedItems={setExternalSelectedItems}
columnDefs={columnDefs}
rowData={rowData}
domLayout={"autoHeight"}
autoSelectFirstRow={true}
/>
</GridWrapper>
</GridContextProvider>
```
=> External grid filters

src/stories/grid/GridReadOnly.stories.tsx
BREAKING CHANGE: release filters
QuickFilter moved out of grid and is now it's own component.
Ability to add external filters added.
```
<GridContextProvider>
<GridWrapper>
<GridFilters>
<GridFilterQuick quickFilterPlaceholder={"Custom placeholder..."} />
<div>
Custom filter: Age less than:
<GridFilterLessThan field={"age"} />
</div>
</GridFilters>
<Grid
{...props}
selectable={true}
externalSelectedItems={externalSelectedItems}
setExternalSelectedItems={setExternalSelectedItems}
columnDefs={columnDefs}
rowData={rowData}
domLayout={"autoHeight"}
autoSelectFirstRow={true}
/>
</GridWrapper>
</GridContextProvider>
```
BREAKING CHANGE: release filters
=> BREAKING CHANGE: release filters

package.json
BREAKING CHANGE: Make ag-grid-community and ag-grid-react peer dependencies so they are omitted from the rollup bundle, and can be upgraded independently.
Post merge
**refactor**: A code …
=> feat!: move ag-grid-community and ag-grid-react to peerDependencies

src/components/Grid.tsx
* if grid.rowSelect is undefined header does not show select-all checkbox
=> Fix if rowSelect multiple not specified header doesnt show selectall

src/components/Grid.tsx
relates to #259 
- Allow users to configure `suppressColumnVirtualization`
- Allow users to override `onFirstDataRendered` and `onGridSizeChanged` callbacks (default to existing behavior of `sizeColumnsToFit`).
Post merge
=> feat(column sizing): make onGridSizeChanged, onFirstDataRendered, and suppressColumnVirtualization configurable

src/components/Grid.tsx
onGridSizeChanged, onFirstDataRendered, suppressColumnVirtualization all have defaults and should not be required.
Post merge
=> fix(GridProps): make optional properties optional

README.md, src/components/Grid.tsx, src/components/GridCell.tsx, src/components/gridFilter/GridFilterDownloadCsvButton.tsx, src/components/gridFilter/GridFilterHeaderIconButton.tsx, src/components/gridFilter/GridFilterQuick.tsx, src/components/gridFilter/index.ts, src/components/gridPopoverEdit/GridPopoverMenu.tsx, src/components/gridRender/GridRenderGenericCell.tsx, src/contexts/GridContext.tsx, src/contexts/GridContextProvider.test.tsx, src/contexts/GridContextProvider.tsx, src/stories/grid/GridPopoverEditBearing.stories.tsx, src/stories/grid/GridPopoverEditDropDown.stories.tsx, src/stories/grid/GridReadOnly.stories.tsx, src/styles/Grid.scss
SURVEY-6191 download grid as CSV
Implement ag-grids download functionality into step ag-grid.
* Added button <GridFilterDownloadCsvButton fileName={"exportFile"}/>
* Added custom processor for cells to return valueFormatter not valueGetter
* Fixed up styles to conform to UIX design
* Fixed waitForExternallySelectedItemsToBeInSync not working.
* Turn on maintainColumnOrder={true} by default on grid to stop columns resetting on update.
=> SURVEY-6191 download grid as CSV

README.md, src/components/Grid.tsx, src/components/GridCell.tsx, src/components/GridPopoverHook.tsx, src/components/gridForm/GridFormDropDown.tsx, src/components/gridPopoverEdit/GridPopoverMenu.tsx, src/contexts/GridContext.tsx, src/contexts/GridContextProvider.tsx, src/contexts/GridUpdatingContext.tsx, src/contexts/GridUpdatingContextProvider.tsx, src/react-menu3/components/MenuList.tsx, src/stories/grid/GridPopoutEditGenericTextArea.stories.tsx, src/stories/grid/GridPopoverEditDropDown.stories.tsx, src/stories/grid/interactions/GridKeyboardInteractions.stories.tsx
* Tab whilst editing edits next/previous field
* Callback for when editing completes
* User sized columns don't resize
* Fixed resize not working when first selected row is scrolled into view
* Fix too many auto size callbacks
* Fix poppedout doesn't auto size
* Auto size changed column after edit
* Fixed when adding the first row to grid resizing doesn't work
=> Tab whilst editing edits next available field

src/components/Grid.tsx, src/contexts/GridContextProvider.tsx, src/lui/timeoutHook.tsx
* default grid size is not auto, not auto-ignore-headers
* select column is now default pinned to left.
* grid auto size that happens when grid is not visible is deferred until grid is onscreen
* columns when they become visible are auto sized
=> Pinned columns, deferred resize

src/components/Grid.tsx, src/contexts/GridContext.tsx, src/contexts/GridContextProvider.tsx
As part of new functionality in [SURVEY-17202](https://toitutewhenua.atlassian.net/browse/SURVEY-17202), we need the ability to place individual cells into edit mode programmatically. This exposes this functionality on the GridContextProvider.
Post merge …
=> SURVEY-17202 adding the ability to place a cell in editing mode

src/components/Grid.tsx, src/contexts/GridContextProvider.tsx
This PR adds the ability to switch off sorting for a grid, and also changes the order for startCellEdit for better backwards compatibility
Story: https://toitutewhenua.atlassian.net/browse/SURVEY-17202
=> Feature/SURVEY-17202 add ability to switch off column sorting for a whole table.

src/components/Grid.tsx
Reverting Grid.startCellEditing to fix failing front-end tests tests in landonline-survey repo. Quite a few tests over there are coupled to this original implementation
=> fix/SURVEY-17202 revert Grid.startCelLEditing back to it's original

src/stories/grid/gridFormInteraction/GridFormEditBearingCorrectionInteraction.stories.tsx, src/utils/bearing.test.ts, src/utils/bearing.ts
Allow showing zero seconds if necessary (Bearing correction case)
Post merge
**test**: Adding missing tests or …
=> feat: SURVEY-17487 Optional show zero seconds

src/utils/textValidator.test.ts, src/utils/textValidator.ts, src/utils/util.test.ts, src/utils/util.ts
* Added notZero to the number format validator.
* Changed number format errors to use .toLocaleString() so we get commas in numbers, e.g. 10,000,000 for 10 million.
* Allow "1." as a valid number so error doesn't occur whilst typing number
=> Add not zero validation to numbers

src/components/Grid.tsx
Story: SURVEY-16691
Task: SURVEY-17749
In some circumstances the cells would not size and would display at the default (with an ellipse if the cell was oversize).
Change here is to not try and resize grids until all the columns are visible as `autoSizeColumns` will fail silently in this case.
Before:
After:
Post merge
**ci**: Changes to our CI configuration files and scripts (example scopes: Circle, BrowserStack, …
=> fix(step-ag-grid): SURVEY-16691: Ensure grid cells get initial size at start

src/contexts/GridContextProvider.tsx
Story: [SURVEY-18038](https://toitutewhenua.atlassian.net/browse/SURVEY-18028)
Ensure that any previous selections are cleared when you add a new empty row or new purpose. Below animated gif shows it's use in actin.
Post merge
**perf**: A …
=> fix: SURVEY-18028 clear selections after adding a new row

package-lock.json, package.json, src/utils/util.test.ts, src/utils/util.ts
npm librarys for sanitizing filenames are causing too many issues due to use of node libs.
This is our own implemention of sanitize filename.
=> Remove sanitize filename due to use of buffer

package-lock.json, package.json, src/utils/testUtil.ts
Ads missing `await` to the now async `userEvent.click()`
Post merge
**test**: Adding missing tests or correcting …
=> fix: SYRVEY-15720 Add missing awaits

src/utils/testUtil.ts
The `closeMenu` and `closePopover` should be using the customised user event so that the await works properly.
Post merge
**refactor**: A code change that neither fixes a bug nor adds a …
=> fix: SURVEY-15720 Change to use customised user event

src/contexts/GridContextProvider.tsx
redraw rows can throw exceptions in jest, so we ignore them
=> Ignore redrawRows exceptions

src/components/Grid.tsx
Popout windows aren't picking up the css grid height consistently, so we pass grid height manually as well as with scss
=> Set default grid height to match grid scss

src/components/GridPopoverHook.tsx, src/react-menu3/components/ControlledMenu.tsx, src/react-menu3/types.ts
It breaks grids within modals
So an issue has popped in in step-ag-grid that if you have a grid inside a LuiModal it won't close/save on clicking outside the dialog.
This was due to some hacked in code to stop the grid popups from closing when a LuiModal OK/Cancel appeared, as the dialog would take focus from the grid.
I'm going to remove this code as there's an alternate way of doing this, specifically in your onSave handler you should return a promise if it's going to show a dialog, and resolve the promise when the dialog is approved.
=> Remove closeMenuExclusionClassName

src/components/Grid.tsx, src/stories/grid/GridDragRow.stories.tsx, src/styles/Grid.scss, src/styles/GridTheme.scss
[SURVEY-18002](https://toitutewhenua.atlassian.net/browse/SURVEY-18002) requires drag/drop row ordering. This PR makes the AG grid drag/drop features accessible to applications.
Post merge …
=> feat: enabled drag/drop moving rows

src/react-menu3/components/ControlledMenu.tsx
When modal dialogs show, on user interaction, the underlying popups close.
This is a temporary fix, await react-menu rewrite.
=> Fix modal dialog issues

src/styles/GridTheme.scss
Centering of selection checkbox was altered by row drag feature PR. This PR reverts some of the CSS changes for that feature and adds padding to the header checkbox so that it lines up when the row grabber is present.
Post merge
**perf**: …
=> fix: select column checkbox now centered correctly in row and header

src/components/Grid.tsx, src/stories/grid/GridDragRow.stories.tsx, src/styles/GridTheme.scss
Managed row dragging in AG Grid moves the row before the onRowDragEnd is fired. This works fine is most scenarios but when needing to cancel from a dialog that pops up on edit, undoing that move was proving to be difficult. This PR switches the row dragging to unmanaged and adds some handlers for the drag events calling the same methods for highlighting the row on move/leave and calculating the target index on drag end.
Post merge
**build**: Changes that affect the build system or external dependencies (example scopes: gulp, …
=> fix: row drag moving row prematurely

src/components/Grid.tsx, src/styles/GridTheme.scss
Multiple themes step on each other.
This is a hack to prevent that.
=> Fix multi themes 2

src/styles/GridTheme.scss
This PR makes the drag placement highlight for row dragging more visible and use a lui colour. Based on feedback from Andi.
Post merge
**refactor**: A code change that neither fixes a bug …
=> fix: made row drag highlight more visible

src/components/Grid.tsx, src/styles/GridTheme.scss
Fixes a couple of minor row drag issues
* Tweaks the css so that the top and bottom row highlights display in the same place so it doesn't 'jitter' when moving between two rows
* Do not show the row highlight if the current target index would result in no move occurring
Post merge …
=> fix: made row drag highlight less 'jittery' and only show when it would result in a change

src/contexts/GridContextProvider.tsx
We're getting this error in prod.  Could only be because getModel() is returning null
```
Cannot read properties of undefined (reading 'isRowsToRender')
```
=> Fix model can be null

src/react-menu3/components/ControlledMenu.tsx
When pressing escape in survey capture the key event handler doesn't stop propagation thus escape key also deselects everything on the map as well as closing the popup.
* escape handled on keyup, not keydown
* keyup event uses stop propogation/prevent default
This is listed as breaking change just in case people are expecting keydown to be blocked.
=> BREAKING_CHANGE: stop events propagation on escape, escape handled on keyup not keydown

src/utils/testUtil.ts
Use getQuick for the regexp test otherwise it could timeout erroneously
=> FIX: Use getQuick for the regexp test otherwise it could timeout erroneously

src/components/GridNoRowsOverlay.tsx
This happens in jest test, added forward refs to fix.
=> FIX: failed to render in 1000ms warning

package-lock.json, src/components/gridPopoverEdit/GridPopoutEditMultiSelect.ts, src/components/gridPopoverEdit/GridPopoutEditMultiSelectGrid.ts, src/components/gridPopoverEdit/GridPopoverEditDropDown.ts
Fix for supporting customized className in GridFormDropDown.tsx
Issue happens in VectorPanel, it has a customized className, but GridCell default className `GridPopoverEditDropDown-containerLarge` was override by it, so move it to the last line in the editorParams to avoid override
[SURVEY-24640](https://toitutewhenua.atlassian.net/browse/SURVEY-24640)
[B] CSD ref field in Vectors panel is missing scroll bar
Post merge …
=> fix: support customized defined className

src/contexts/GridContextProvider.tsx, src/stories/grid/GridReadOnly.stories.tsx
Ag-grid has a bug where if a focused cell comes into view after a filter the filter loses focus.
To prevent this I clear the focus after filter
=> fix: custom filter loses focus after filter

.github/dependabot.yml
This pull request is opened automatically by [linz/security-gha-scan](https://github.com/linz/security-gha-scan) to ensure that the usage of Github Actions meets [LINZ security requirements](https://toitutewhenua.atlassian.net/wiki/x/h5SRHQ).
Please review and merge it as soon as possible, contact [#team-step-security](https://linz.enterprise.slack.com/archives/C03278T3HCK) or [#team-step-enablement](https://linz.enterprise.slack.com/archives/CMP0BQ2V7) if you have any question.
=> chore: auto update Github actions except for unverified ones

src/components/gridPopoverEdit/GridEditBoolean.tsx
A simple update that inserts a new conditional css class in the `GridEditBoolean` Component when the child input is in a disabled state.
Required for overriding styles on inputs that are disabled in story [SRVPUW-1063](https://toitutewhenua.atlassian.net/browse/SRVPUW-1063)
Post merge
**docs**: Documentation only …
=> feat: add ag-disabled css conditional class to GridEditBoolean

src/components/gridPopoverEdit/GridEditBoolean.tsx
If grid data is updated whilst editing the editor uses the wrong underlying data.
=> fix: stale data being used by boolean editor

src/lui/FormError.scss, src/lui/FormError.tsx, src/lui/TextInputFormatted.scss
As Andi's require:
- change format text to fuscous
- include error icon on error
- change error text colour to charcoal
- 
Post merge
**refactor**: A code change that neither fixes a bug …
=> feat: SURVEY-25913 text input format error

src/components/Grid.tsx
Drag highlight was using document.querySelector not grid.querySelector to apply styles, thus would affect all grids in app.
=> fix: Drag highlight isn't limited to target grid

src/components/Grid.tsx, src/components/clickInputWhenContainingCellClicked.tsx
fix: clickInputWhenContainingCellClicked doesn't work if row selection is on
the click conflicts with the row selection click handler
=> fix: clickInputWhenContainingCellClicked doesn't work if row selection is on

src/utils/__tests__/testUtil.ts
Double clicking to open menus causes intermittent failures.
=> fix: single click to open menus

src/components/Grid.tsx
If you add quotes to quick filter search it will do an exact wildcard* match
e.g. "Foo blah" matches "Foo blah", "Foo blah blop" but not "Foo blop blah"
=> feat: Quick filter exact with quotes

src/components/Grid.tsx
Filter is exact match unless separated by commas.
So:
"abc,xyz" will filter for "abc" and "xyz"
"abc xyz" will filter for "abc xyz"
=> feat: Filter is exact match unless separated by commas

src/components/GridCell.tsx
fix: empty string formatted value should substitute emdash "" => "-"
=> fix: empty string should substitute emdash

src/components/Grid.tsx
Possible reason panels aren't resizing in survey internal.
=> fix: auto-skip-headers does not callback for size
