linz/step-ag-grid

- src/components/GridCell.tsx
- src/components/gridRender/GridRenderGenericCell.tsx
> fix: cellrenderer is missing warning and info

- index.ts
- package-lock.json
- package.json
- src/react-menu3/components/ControlledMenu.tsx
- src/react-menu3/components/MenuHeader.tsx
- src/react-menu3/positionUtils/positionMenu.ts
- src/react-menu3/types.ts
> fix: Export all types from react menu, fix: MenuHeader not having children property

- index.ts
- src/components/GridCell.tsx
- src/components/GridPopoverHook.tsx
- src/components/gridForm/GridFormEditBearing.tsx
- src/components/gridPopoverEdit/GridPopoverEditBearing.ts
- src/react-menu3/components/MenuList.tsx
- src/react-menu3/types.ts
- src/stories/components/GridPopoutBearing.stories.tsx
- src/utils/bearing.ts
fix: bearing validation not working
Post merge
> fix: bearing validation not working, feat: added don't shrink if menu direction is top option

- index.ts
- src/components/GridCell.tsx
- src/components/gridForm/GridFormTextInput.tsx
- src/lui/TextInputFormatted.tsx
- src/stories/components/FormTest.tsx
- src/stories/components/GridPopoutEditGenericTextArea.stories.tsx
> fix: Add units to textInputFormatter

- index.ts
- src/components/Grid.tsx
- src/components/gridForm/GridFormMultiSelect.tsx
- src/components/gridForm/GridFormPopoutMenu.tsx
- src/components/gridForm/GridFormTextInput.tsx
- src/contexts/GridContext.tsx
- src/contexts/GridContextProvider.tsx
fix: pass data back to validate
fix: defaultColDef not required
fix: export menu separator
fix: resize columns on column number change
Post merge
**refactor**: A code change that neither …
> fix: pass data back to validate, fix: defaultColDef not required

- src/components/GridPopoverHook.tsx
- src/contexts/GridContextProvider.tsx
> fix: remove position initial from popup menu

- src/components/gridForm/GridFormDropDown.tsx
BREAKING CHANGE: deploy to npm
> BREAKING CHANGE: deploy to npm

- package.json
- src/components/Grid.tsx
- src/stories/components/GridPopoutBearing.stories.tsx
- src/stories/components/GridPopoutEditDropDown.stories.tsx
- src/stories/components/GridPopoutEditGeneric.stories.tsx
- src/stories/components/GridPopoutEditGenericTextArea.stories.tsx
- src/stories/components/GridPopoutEditMultiSelect.stories.tsx
- src/stories/components/GridReadOnly.stories.tsx
feat: add npm keywords
feat: add story controls for selectable
Post merge
**test**: Adding missing tests or …
> feat: add npm keywords, add story controls for selectable

- README.md
- src/stories/components/GridPopoutEditDropDown.stories.tsx
fix: readme code example
Post merge
> fix: readme code example

- README.md
fix: storybook url no longer private
Post merge
> fix: storybook url no longer private

- package-lock.json
- package.json
fix: add missing package conventional-changelog-conventionalcommits for deployments
Post merge …
> fix: add missing package conventional-changelog-conventionalcommits

- README.md
- package.json
> fix: temp-remove-semantic-config-until-fix-available

- src/components/GridPopoverHook.tsx
- src/index.ts
- src/react-menu3/components/ControlledMenu.tsx
- src/react-menu3/types.ts
fix: export missing types from forms
fix: don't close menu if modal dialog is open
Post merge …
> fix: export missing types from forms, fix: don't close menu if modal dialog is open

- src/stories/grid/FormTest.tsx
> fix: modals no longer closed by onBlur of menu

- src/components/GridSubComponentTextArea.tsx
- src/components/gridForm/GridFormDropDown.tsx
- src/components/gridForm/GridFormMultiSelect.tsx
- src/components/gridForm/GridFormTextInput.tsx
- src/components/gridForm/GridSubComponentProps.ts
- src/components/gridPopoverEdit/GridPopoutEditMultiSelect.ts
- src/components/gridPopoverEdit/GridPopoverEditBearing.ts
- src/components/gridPopoverEdit/GridPopoverEditDropDown.ts
- src/components/gridPopoverEdit/GridPopoverMessage.ts
- src/components/gridPopoverEdit/GridPopoverTextArea.ts
- src/components/gridPopoverEdit/GridPopoverTextInput.ts
- src/lui/TextInputFormatted.tsx
- src/stories/grid/GridPopoutEditMultiSelect.stories.tsx
* Can now pass a Record<value, subComponentValue> as intial values.
* Save method now returns (selectedRows[], SelectedOptionResult[])
* Subcomponents now sync values
* Removed hard coded sizes on grid cells.
Post merge
**perf**: A code …
> feat: add initial values object to multi drop down, implement subcomponents, altered save signature

- src/react-menu3/components/ControlledMenu.tsx
- src/stories/grid/FormTest.tsx
> fix: ControlledMenu error

- src/components/GridSubComponentTextArea.tsx
- src/components/gridForm/GridFormMultiSelect.tsx
- src/components/gridForm/GridFormTextArea.tsx
- src/components/gridForm/GridFormTextInput.tsx
- src/components/gridForm/GridSubComponentProps.ts
- src/contexts/GridSubComponentContext.ts
- src/stories/components/ActionButton.stories.tsx
- src/stories/grid/FormTest.tsx
- src/stories/grid/GridPopoutBearing.stories.tsx
- src/stories/grid/GridPopoutEditDropDown.stories.tsx
- src/stories/grid/GridPopoutEditGeneric.stories.tsx
- src/stories/grid/GridPopoutEditGenericTextArea.stories.tsx
- src/stories/grid/GridPopoutEditMultiSelect.stories.tsx
- src/stories/grid/GridReadOnly.stories.tsx
feat: improved subComponents using a context
fix: renamed maxlength to maxLength
Post merge
**test**: Adding missing …
> feat: improved subComponents using a context

- src/components/gridForm/GridFormSubComponentTextInput.tsx
- src/stories/grid/GridPopoutEditDropDown.stories.tsx
fix ci issues on master
Post merge
**refactor**: A code change that neither fixes a bug nor adds a …
> fix: ignore unexpected console in story

- src/components/gridForm/GridFormSubComponentTextInput.tsx
Add a default width to input subcomponent, add an optional className as a prop
Post merge
**refactor**: …
> fix: apply styles to text input

- package.json
- src/components/gridForm/GridFormPopoverMenu.tsx
- src/components/gridPopoverEdit/GridPopoverMenu.tsx
- src/contexts/GridContextProvider.tsx
- src/index.ts
- src/react-menu3/components/ControlledMenu.tsx
- src/react-menu3/components/Menu.tsx
- src/react-menu3/components/MenuButton.tsx
- src/react-menu3/components/MenuGroup.tsx
- src/react-menu3/components/MenuItem.tsx
- src/react-menu3/components/SubMenu.tsx
- src/react-menu3/hooks/useBEM.ts
> fix: remove todos

- src/components/gridForm/GridFormDropDown.tsx
- src/components/gridForm/GridFormSubComponentTextInput.tsx
- src/styles/GridFormSubComponentTextInput.scss
* allow subcomponent to save on tab
* remove keys error from GridFormDropdown
* add help text to input based on feedback
* add some default styling to Subcomponent text input
Post merge
**feat**: A …
> fix: allow subcomponent to save on tab

- src/components/gridForm/GridFormDropDown.tsx
- src/components/gridForm/GridFormSubComponentTextInput.tsx
* change the onKeydown save function to close menu after save operation has completed
* ensure enclosing div is full width
Post merge
**perf**: A code …
> fix: subcomponet close after save

- src/components/gridForm/GridFormDropDown.tsx
- src/components/gridForm/GridFormSubComponentTextInput.tsx
* pass input event to keydown callback
* call event.preventDefault and stopPropagation
Post merge …
> fix: pass event to keydown

- src/components/gridForm/GridFormDropDown.tsx
* remove line that breaks ci
Post merge
**refactor**: A code change that neither fixes a bug nor adds a …
> fix: remove breaking line

- src/lui/TextInputFormatted.tsx
> feat: Added props onFocus and onClick to component TextInputFormatted

- src/components/gridForm/GridFormMultiSelect.tsx
- src/stories/grid/GridPopoutEditMultiSelect.stories.tsx
Save on unneeded updates by only saving if dirty.
> fix: multi select now wont save if data hasnt changed

- src/react-menu3/components/MenuList.tsx
React menu doesn't seem to reposition on window resize, so I've added a resize observer.
Post merge …
> fix: react menu window resize observer

- src/index.ts
> fix: missing context exports

- .prettierrc.js
- src/components/Grid.tsx
- src/components/GridCell.tsx
- src/components/GridPopoverHook.tsx
- src/components/gridForm/GridFormDropDown.tsx
- src/components/gridForm/GridFormEditBearing.tsx
- src/components/gridForm/GridFormMultiSelect.tsx
- src/components/gridForm/GridFormPopoverMenu.tsx
- src/components/gridForm/GridFormSubComponentTextArea.tsx
- src/components/gridForm/GridFormSubComponentTextInput.tsx
- src/components/gridForm/GridFormTextArea.tsx
- src/components/gridForm/GridFormTextInput.tsx
- src/contexts/GridPopoverContextProvider.tsx
- src/contexts/GridSubComponentContext.ts
- src/index.ts
- src/lui/TextAreaInput.tsx
- src/lui/TextInputFormatted.tsx
- src/react-menu3/components/MenuItem.tsx
- src/stories/grid/FormTest.tsx
- src/stories/grid/GridPopoutEditDropDown.stories.tsx
- src/stories/grid/GridPopoutEditMultiSelect.stories.tsx
- src/stories/grid/GridReadOnly.stories.tsx
- src/utils/textValidator.ts
feat: remove inputprops on input/textarea and combine into root object
fix: if you edit a non-selected row via keyboard events the selectedRows is empty or incorrect
feat: common keyboard handlers for tab and edit inside 
fix: don't close menus onBlur (it breaks dialogs)
fix: dropdown sub components not working
> feat: inputProps removed, fix row selection via keyboard, feat common keyboard handlers

- src/components/gridForm/GridFormDropDown.tsx
- src/components/gridForm/GridFormMultiSelect.tsx
- src/components/gridForm/GridFormPopoverMenu.tsx
- src/components/gridForm/GridFormSubComponentTextArea.tsx
- src/components/gridForm/GridFormSubComponentTextInput.tsx
- src/components/gridForm/GridFormTextArea.tsx
- src/components/gridForm/GridFormTextInput.tsx
- src/contexts/GridSubComponentContext.ts
- src/utils/textValidator.ts
fix: missing data on custom validate
> fix: missing data on custom validate

- package-lock.json
- src/components/GridPopoverHook.tsx
- src/components/gridForm/GridFormDropDown.tsx
- src/components/gridForm/GridFormEditBearing.tsx
- src/components/gridForm/GridFormMultiSelect.tsx
- src/components/gridForm/GridFormPopoverMenu.tsx
- src/components/gridForm/GridFormSubComponentTextArea.tsx
- src/components/gridForm/GridFormSubComponentTextInput.tsx
- src/components/gridForm/GridFormTextArea.tsx
- src/components/gridForm/GridFormTextInput.tsx
- src/contexts/GridContext.tsx
- src/contexts/GridContextProvider.tsx
- src/contexts/GridPopoverContext.tsx
- src/contexts/GridPopoverContextProvider.tsx
- src/contexts/GridUpdatingContext.tsx
- src/contexts/GridUpdatingContextProvider.tsx
- src/lui/FormError.tsx
- src/lui/TextAreaInput.tsx
- src/lui/TextInputFormatted.tsx
- src/react-menu3/components/ControlledMenu.tsx
- src/react-menu3/components/MenuItem.tsx
- src/react-menu3/types.ts
- src/react-menu3/utils/constants.ts
- src/stories/grid/FormTest.tsx
- src/stories/grid/GridPopoutEditDropDown.stories.tsx
- src/stories/grid/GridPopoutEditMultiSelect.stories.tsx
- src/stories/grid/GridReadOnly.stories.tsx
- src/styles/GridFormDropDown.scss
BREAKING CHANGE: implement tab to finish edit, replace manual keyboard handler with auto
> BREAKING CHANGE: implement tab to finish edit, replace manual keyboard handler with auto

- src/react-menu3/components/ControlledMenu.tsx
> fix: tab on multi selects

- src/components/GridPopoverHook.tsx
- src/components/gridForm/GridFormDropDown.tsx
- src/components/gridForm/GridFormPopoverMenu.tsx
- src/components/gridPopoverEdit/GridPopoverEditDropDown.ts
- src/contexts/GridContext.tsx
- src/contexts/GridContextProvider.tsx
- src/contexts/GridPopoverContextProvider.tsx
- src/react-menu3/components/ControlledMenu.tsx
- src/stories/grid/GridPopoutEditDropDown.stories.tsx
- src/stories/grid/GridPopoutEditGenericTextArea.stories.tsx
- src/stories/grid/GridReadOnly.stories.tsx
- src/utils/bearing.ts
- src/utils/textValidator.ts
* fix double submit on popups/dropdown
* added maxBytes to textinputs/areas validation
* add custom trim logic for whitespaces to validator / text input
* fix tab when user has already selected
* Removed valuetype off popover edit dropdown
> BREAKING CHANGE: validate now invalid, removed valueType generic off popoverEditDropdown

- src/react-menu3/components/ControlledMenu.tsx
- src/stories/grid/FormTest.tsx
> feat: added disableEnterAutoSave flag

- src/lui/ActionButton.scss
- src/lui/ActionButton.tsx
- src/react-menu3/components/ControlledMenu.tsx
- src/stories/components/ActionButton.stories.tsx
- src/stories/grid/FormTest.tsx
> fix: Action button sizing

- src/components/gridForm/GridFormDropDown.tsx
- src/stories/grid/GridPopoutEditDropDown.stories.tsx
fix: filter text selection not working in dropdown
> fix: filter text selection not working in dropdown

- src/components/gridForm/GridFormDropDown.tsx
- src/stories/grid/GridPopoutEditDropDown.stories.tsx
fix: filter text selection not working in dropdown
> Fix filter text selection not working in dropdown

- rollup.config.cjs
- src/components/gridForm/GridFormDropDown.tsx
- src/components/gridForm/GridFormMultiSelect.tsx
- src/index.ts
- src/react-menu3/components/ControlledMenu.tsx
- src/utils/testQuick.ts
- src/utils/testUtil.ts
findRow
queryRow
selectRow
deselectRow
findCell
selectCell
editCell
findOpenMenu
queryMenuOption
findMenuOption
clickMenuOption
openAndClickMenuOption
getMultiSelectOptions
findMultiSelectOption
clickMultiSelectOption
typeOtherInput
typeOtherTextArea
closeMenu
findActionButton
clickActionButton
> feat: add support for tests

- src/components/gridForm/GridFormMultiSelect.tsx
- src/components/gridPopoverEdit/GridPopoverEditDropDown.ts
- src/stories/grid/GridPopoutEditMultiSelect.stories.tsx
- src/utils/textMatcher.ts
fix: not filtering in multiselect popover... e.g. !lot
> fix: not filtering in multiselect popover

- .gitattributes
- src/components/gridForm/GridFormDropDown.tsx
- src/stories/grid/GridPopoutEditMultiSelect.stories.tsx
- src/utils/testQuick.ts
- src/utils/testUtil.ts
feat: add cellContains for testing
> feat: add cellContains for testing

- src/components/gridForm/GridFormDropDown.tsx
- src/components/gridForm/GridFormMultiSelect.tsx
- src/components/gridForm/GridFormPopoverMenu.tsx
- src/components/gridForm/GridFormSubComponentTextArea.tsx
- src/utils/testUtil.ts
fix: testutils-not-finding-menu-options-and-subcomponents
> fix: testutils-not-finding-menu-options-and-subcomponents

- src/components/gridForm/GridFormTextArea.tsx
- src/components/gridForm/GridFormTextInput.tsx
- src/contexts/GridContext.tsx
- src/contexts/GridContextProvider.tsx
- src/utils/testUtil.ts
fix: tests not waiting long enough
> fix: tests not waiting long enough

- src/utils/testUtil.ts
feat: rename cellContains to findCellContains, add countrows
> feat: rename cellContains to findCellContains, add countrows

- src/lui/ActionButton.tsx
- src/stories/components/ActionButton.stories.tsx
- src/stories/grid/GridPopoutEditGenericTextArea.stories.tsx
- src/utils/util.ts
feat: ActionButton onAction renamed to onClick, added findParentByClassName
> feat: ActionButton onAction renamed to onClick, added findParentByClassName

- package-lock.json
- package.json
- src/components/Grid.tsx
- src/lui/ActionButton.scss
- src/lui/ActionButton.tsx
- src/stories/components/ActionButton.stories.tsx
- src/stories/grid/GridPopoutBearing.stories.tsx
fix: datatestids sometimes not showing
fix: action button icon rotation and sizing
> fix: datatestids sometimes not showing, action button icon rotation and sizing

- src/components/GridCell.tsx
- src/contexts/GridContextProvider.tsx
- src/contexts/GridPopoverContextProvider.tsx
- src/styles/Grid.scss
- src/styles/GridTheme.scss
- src/utils/deferredPromise.ts
fix: render cells are blank on popover
fix: cancel deferred on unload
fix: catch exceptions in updatingcells
fix: single select highlighting
> fix: render cells are blank on popover, cancel deferred on unload, catch exceptions in updatingcells, fix single select highligh

- src/utils/textValidator.test.ts
- src/utils/textValidator.ts
> feat: add scale to validator

- README.md
- src/stories/grid/GridPopoutBearing.stories.tsx
- src/utils/bearing.ts
Fixed bearing correction formatter
Post merge
> fix: Fix bearing correction

- src/components/Grid.tsx
- src/components/GridCell.tsx
- src/components/gridRender/GridRenderGenericCell.tsx
- src/stories/grid/GridReadOnly.stories.tsx
- src/styles/Grid.scss
feat: hide editable icon on not focused or hovered
feat: shortcut keys for cells
> feat: hide editable icon on not focused or hovered, feat: shortcut keys for cells

- src/stories/grid/GridPopoutBearing.stories.tsx
- src/utils/bearing.ts
> fix: Fixed bearing correction formatter when type string

- src/components/Grid.tsx
- src/stories/grid/GridReadOnly.stories.tsx
With custom edit, if you edit an unselected row it does not select it.
> fix: single row selection on custom edit

- src/components/Grid.tsx
- src/contexts/GridContext.tsx
- src/contexts/GridContextProvider.tsx
- src/stories/grid/GridReadOnly.stories.tsx
feat: auto select first row
feat: wait for external row selection in sync
> feat: auto select first row, and wait for external row selection in sync

- README.md
> docs: Added info to README.md about using testing calls from step-ag-grid

- src/components/Grid.tsx
- src/utils/testUtil.ts
Fix for selecting row in tests may be failing.
> fix: test row selection

- src/utils/testUtil.ts
fix: remove selectRow call from editCell
> fix: remove selectRow call from editCell

- src/styles/GridTheme.scss
fix: multi line cell edit position
> fix: multi line cell edit position

- src/styles/GridTheme.scss
fix: change hover colour to hint
> fix: change hover colour to hint

- src/react-menu3/README.md
> fix: readme change to trigger build

- src/components/Grid.tsx
- src/components/gridHeader/GridHeaderSelect.tsx
- src/contexts/GridContextProvider.tsx
- src/stories/grid/GridPopoutEditGenericTextArea.stories.tsx
fix: header select keyboard events handling
fix: select first cell when selecting new row
> fix: header select keyboard events, and fix select first new cell

- src/components/gridForm/GridFormDropDown.tsx
- src/contexts/GridContextProvider.tsx
- src/contexts/GridPopoverContextProvider.tsx
- src/react-menu3/components/ControlledMenu.tsx
fix: tab from filter should save dropdown
fix: unneeded external selected items updates
> fix: tab from filter should save dropdown, unneeded external selected items updates

- src/react-menu3/components/ControlledMenu.tsx
> fix: disableenterautosave

- src/components/gridForm/GridFormDropDown.tsx
fix: async filtered values are empty because of filter
> fix: async filtered values are empty because of filter

- src/components/gridForm/GridFormDropDown.tsx
fix: no options on async options
> fix: no options on async options

- src/components/Grid.tsx
fix: auto focus first cell on auto select first row
> fix: auto focus first cell on auto select first row

- src/components/Grid.tsx
- src/components/GridCell.tsx
- src/components/GridCellMultiEditor.tsx
- src/components/GridCellMultiSelectClassRules.tsx
- src/components/gridForm/GridFormTextArea.tsx
- src/contexts/GridContext.tsx
- src/contexts/GridContextProvider.tsx
- src/stories/grid/GridPopoutEditGenericTextArea.stories.tsx
- src/styles/GridTheme.scss
feat: Dynamic cell editors
fix: home/end/pageup/pagedown not working
fix: select first cell if autoSelectFirstRowNotSet
> Dynamic cell editors

- src/components/GridCellMultiEditor.tsx
- src/components/gridForm/GridFormDropDown.tsx
- src/components/gridRender/GridRenderGenericCell.tsx
- src/index.ts
- src/stories/grid/GridPopoutEditGenericTextArea.stories.tsx
fix: debounce on getoptions, added row typing to editable
> fix: debounce on getoptions, added row typing to editable

- src/components/gridRender/GridRenderGenericCell.tsx
- src/stories/grid/GridPopoutEditDropDown.stories.tsx
feat: add types to valueFormatter, valueGetter
> feat: add types to valueFormatter, valueGetter

- src/utils/testUtil.ts
Added a test function for entering text into a cell editor's input.
Post merge
**test**: Adding missing tests or …
> feat: added test function for cell editor input

- src/utils/testUtil.ts
Various tests are currently getting the input in an editor in various ways (label, placeholder, single) so this PR adds some test util functions to cover those cases.
Post merge …
> Feat added type input test util functions

- src/utils/testUtil.ts
> fix: wrapping test input userevents in act

- src/utils/testUtil.ts
> fix: adding wait to typeInput calls

- src/utils/testUtil.ts
openAndClickMenuoption was not firing the click event so this PR fixes that issue.
Post merge …
> fix: openAndClickMenuOption was not always firing the click event

- src/utils/testUtil.ts
> fix: added textarea to type input util functions

- src/utils/testUtil.ts
> feat: added reaonly cell check function

- src/utils/testUtil.ts
> fix: fixing readonly check test util function

- src/components/Grid.tsx
- src/stories/grid/GridPopoutBearing.stories.tsx
For internal survey, we always show vertical scroll bar, this PR add and expose that ag-grid props. 
https://toitutewhenua.atlassian.net/browse/SRVTRI-1379
Not sure if I should create a new story, did run `npm run storybook` and see the property was there.
I added to bearings story because we currently showing marks and vectors with the scroll bar.
Post merge
**build**: Changes that affect the build system or external dependencies (example scopes: …
> Feat: Add new prop alwaysShowVerticalScroll

- src/utils/testUtil.ts
Added a openAndFindMenuOption test function as it's a common use case in testing.
Post merge …
> feat: added openAndFindMenuOption test util function

- src/utils/testUtil.ts
export findOpenPopover
make container optional in clickActionButton/findActionButton
> feat: export find popover and make containers optional

- src/utils/testUtil.ts
Done as part of the work for [SURVEY-3909](https://toitutewhenua.atlassian.net/browse/SURVEY-3909). Some test functions are logging errors to the console that aren't helpful and clutter up the output.
Post merge
**perf**: A code change …
> fix: test util fixes to clear console errors

- src/components/gridForm/GridFormMultiSelect.tsx
- src/utils/testUtil.ts
Added key to multiselect headers to remove console error.
Post merge
**test**: Adding missing tests or correcting …
> fix: added key to multiselect group headers

- src/components/gridForm/GridFormMultiSelect.tsx
> fix: added group key to multiselect

- src/utils/testUtil.ts
> fix: adding act wrapper to findRow

- src/components/gridForm/GridFormDropDown.tsx
- src/components/gridForm/GridFormPopoverMenu.tsx
- src/components/gridPopoverEdit/GridPopoverMenu.tsx
- src/lui/ActionButton.tsx
- src/react-menu3/styles/index.scss
- src/stories/components/ActionButton.stories.tsx
- src/stories/grid/gridForm/GridFormDropDown.stories.tsx
- src/stories/grid/gridForm/GridFormEditBearing.stories.tsx
- src/stories/grid/gridForm/GridFormEditBearingCorrection.stories.tsx
- src/stories/grid/gridForm/GridFormMessage.stories.tsx
- src/stories/grid/gridForm/GridFormPopoverMenu.stories.tsx
- src/stories/grid/gridForm/reactMenuTest.scss
feat: add disabled flag to ActionButton
Also added storybook tests for other components
> feat: add disabled flag to actionbutton

- src/components/GridCell.tsx
- src/components/gridForm/GridFormDropDown.tsx
- src/components/gridForm/GridFormEditBearing.tsx
- src/components/gridForm/GridFormMultiSelect.tsx
- src/components/gridPopoverEdit/GridPopoverEditBearing.ts
- src/components/gridPopoverEdit/GridPopoverEditDropDown.ts
- src/react-menu3/styles/_var.scss
- src/stories/grid/gridForm/GridFormDropDown.stories.tsx
- src/stories/grid/gridForm/GridFormEditBearing.stories.tsx
- src/stories/grid/gridForm/GridFormEditBearingCorrection.stories.tsx
- src/stories/grid/gridForm/GridFormMessage.stories.tsx
- src/stories/grid/gridForm/GridFormMultiSelect.stories.tsx
- src/stories/grid/gridForm/GridFormTextArea.stories.tsx
- src/stories/grid/gridForm/GridFormTextInput.stories.tsx
- src/styles/Grid.scss
- src/styles/GridFormMultiSelect.scss
- src/styles/GridIcon.scss
- src/styles/lui-overrides.scss
- src/styles/react-menu-customisations.scss
- src/utils/bearing.test.ts
- src/utils/bearing.ts
fix: GridFormTests
feat: warnings and info now use outlines
feat: Andi's new styles
> fix: GridFormTests

- src/components/Grid.tsx
- src/contexts/GridContext.tsx
- src/contexts/GridContextProvider.tsx
fix focus lost on dialogs/popups closing
> fix focus lost on dialogs

- src/components/GridPopoverHook.tsx
- src/components/gridForm/GridFormDropDown.tsx
- src/stories/grid/GridReadOnly.stories.tsx
fix: dropdown should not save on blur
> fix: dropdown should not save on blur

- src/components/GridCell.tsx
- src/components/gridForm/GridFormDropDown.tsx
- src/components/gridRender/GridRenderGenericCell.tsx
feat: Filters should filter from formatted value not getter.
feat: Allow string[] for warning/info
> feat: Create default filter value getter if there's a value formatter

- config/jest/setup.js
- package-lock.json
- package.json
- src/components/GridCell.test.tsx
- src/components/GridCell.tsx
- src/components/gridRender/GridRenderGenericCell.tsx
- src/setupTests.ts
- src/stories/grid/GridPopoutBearing.stories.tsx
AgGrid defaults to filtering on getters, this changes it to use formatters and getters (if string type).
> Use getter values as well as formatted for filter

- .npmrc
- src/components/gridForm/GridFormDropDown.tsx
- src/components/gridForm/GridFormMultiSelect.tsx
fix wrong relative path to context which is breaking lint in survey
> fix wrong relative path to context

- package-lock.json
- package.json
- src/components/GridCell.tsx
- src/react-menu3/hooks/useMenuState.ts
BREAKING CHANGE: Move aggrid peerdeps to deps
aggrid libs are now included with step-ag-grid
You can remove "ag-grid-community", "ag-grid-react" from your project deps.
> BREAKING CHANGE: Move aggrid peerdeps to deps

- src/stories/grid/gridFormInteraction/GridFormMultiSelectInteraction.stories.tsx
* fix multi select test flakyness
* fix test enter to save filter
> multi select test flakyness, text enter to save filter

- src/components/Grid.tsx
> dont show row selection header when row selection is set to single

- src/components/GridFilter.ts
- src/components/gridFilter/GridFilterButtons.tsx
- src/contexts/GridContext.tsx
- src/contexts/GridContextProvider.tsx
- src/stories/grid/GridReadOnly.stories.tsx
```
<GridFilterButtons<ITestRow>
options={[
{
label: "All",
defaultSelected: true,
},
{
label: "< 30",
filter: (row) => row.age < 30,
},
]}
/>
```
> GridFilterButtons

- src/components/GridFilter.ts
- src/components/gridFilter/GridFilterButtons.tsx
- src/contexts/GridContext.tsx
- src/contexts/GridContextProvider.tsx
- src/stories/grid/GridReadOnly.stories.tsx
```
<GridFilterButtons<ITestRow>
options={[
{
label: "All",
defaultSelected: true,
},
{
label: "< 30",
filter: (row) => row.age < 30,
},
]}
/>
```
> feat: GridFilterButtons

- src/stories/grid/GridReadOnly.stories.tsx
Fix lint issue double imported component
> Fix lint issue double import

- README.md
BREAKING CHANGE: ag-grid-community and ag-grid-react are now peerDependencies which must be installed separately.  This allows consuming projects to upgrade to a newer version if desired.
Post merge
**docs**: Documentation only …
> feat: Make ag-grid-community and ag-grid-react peerDependencies

- README.md
* Add grid column toggle
* Change non-editable color to fuscous
* Expose global method for playwright to scrolling rows into view.
> Release features, column toggle, pw support

- src/components/gridFilter/GridFilterColumnsToggle.tsx
Non visibility controlled columns should not allow disabling.
> fix: can toggle disabled columns

- src/components/Grid.tsx
- src/components/GridNoRowsOverlay.tsx
- src/components/GridNoRowsOverlayComponent.tsx
- src/components/index.ts
- src/stories/grid/GridNoRowsOverlay.stories.tsx
- src/stories/grid/interactions/GridKeyboardInteractions.stories.tsx
Fixed no rows overlay to be an actual component, otherwise it does not update with data changes.
> Fix no rows present not displaying correctly

- src/components/Grid.tsx
This will enable consumer of this lib to test out different ag-grid themes (https://www.ag-grid.com/javascript-data-grid/global-style-customisation-sass/#multiple-themes).
Post merge …
> feat: allow override theme prop

- package-lock.json
- package.json
- src/contexts/GridContextProvider.tsx
- src/stories/grid/GridReadOnly.stories.tsx
- src/utils/util.test.ts
- src/utils/util.ts
This just removes weird characters and trims filenames passed to CSV Download
> Download CSV Filename sanitisation and tests

- src/styles/Grid.scss
Change padding and size of quick filter
> Change padding and size of quick filter

- package-lock.json
- package.json
- src/components/GridCell.tsx
- src/components/gridFilter/GridFilterDownloadCsvButton.tsx
- src/styles/GridCell.scss
* Upgrade lui
* Download icon replaced with CSV Icon
* Set grid cell width to 100%
> Change csv icon fix grid cell width, add tooltip to header

- src/components/Grid.tsx
* Change default resize to auto skip headers
* Auto size grid when resizing columns
> Change default resize to auto skip headers, Auto size grid when resizing columns

- src/components/Grid.tsx
- src/contexts/GridContextProvider.tsx
Fix:
* excessively grid size callbacks
* grid size now ignores hidden columns
> Fix excessively grid size callbacks and grid size now ignores hidden columns 

- src/components/Grid.tsx
Default select pinned column to left breaks too many tests
> default select pinned column to null

- src/contexts/GridContextProvider.tsx
Fix: tabbing from start or end of grid during edit incorrectly re-edits same field
> Fix tab from start or end of grid incorrectly edits

- src/components/Grid.tsx
- src/contexts/GridContext.tsx
- src/contexts/GridContextProvider.tsx
- src/contexts/GridUpdatingContext.tsx
- src/contexts/GridUpdatingContextProvider.tsx
Change logic for autosize updated columns to be driven off the updating context.
> Fix updating dependant column autosize

- README.md
- package-lock.json
- package.json
- src/components/Grid.tsx
- src/components/gridForm/GridFormMultiSelectGrid.tsx
- src/components/gridForm/index.ts
- src/components/gridPopoverEdit/GridPopoutEditMultiSelectGrid.ts
- src/components/gridPopoverEdit/index.ts
- src/react-menu3/components/MenuItem.tsx
- src/react-menu3/components/MenuList.tsx
- src/react-menu3/contexts/HoverItemContext.ts
- src/react-menu3/hooks/useItems.ts
- src/react-menu3/utils/withHovering.tsx
- src/stories/grid/GridPopoverEditMultiSelectGrid.stories.tsx
- src/stories/grid/gridFormInteraction/GridFormMultiSelectGridInteraction.stories.tsx
- src/stories/react-menu/ReactMenu.stories.tsx
- src/styles/GridFormMultiSelectGrid.scss
- src/styles/index.scss
- tsconfig.json
> Multi select grid

- src/components/Grid.tsx
- src/components/gridForm/GridFormMultiSelectGrid.tsx
- src/stories/grid/gridFormInteraction/GridFormMultiSelectGridInteraction.stories.tsx
* Support JSX in multiselect grid
* Add rowHeight param to grid
> Support JSX in multiselect grid

- src/components/Grid.tsx
- src/components/gridFilter/GridFilterColumnsToggle.tsx
- src/contexts/GridContext.tsx
- src/contexts/GridContextProvider.tsx
- src/stories/grid/GridReadOnly.stories.tsx
Fixes for group columns:
* Auto-size fixed for ColGroups
* Hopefully fixed popout window auto-size in prod servers
* Fix colDef initialHide value not working
> Fixes for group columns

- README.md
- src/components/GridCellFiller.tsx
- src/components/gridFilter/GridFilterColumnsToggle.tsx
- src/components/gridUtil.ts
- src/components/index.ts
- src/contexts/GridContext.tsx
- src/contexts/GridContextProvider.tsx
- src/stories/grid/GridReadOnly.stories.tsx
* Added filter param to getColumns
* Added get columnIds util
* Added GridCellFiller()
If you add this to your column defs it will become active if no fill columns are visible.
> Add filler column

- package.json
> BREAKING CHANGE: correctly export common js.

- src/utils/testQuick.ts
- src/utils/testUtil.ts
Support React 18 Survey test work
* remove `act` wrapper
* enable external user event to pass in
Post merge …
> fix: SURVEY-15720 support user event v14

- README.md
- src/components/Grid.tsx
- src/contexts/GridContextProvider.tsx
- src/index.ts
- src/stories/grid/GridFilterButtons.stories.tsx
- src/stories/grid/GridNonEditableRow.stories.tsx
- src/stories/grid/GridPopoutContextMenu.stories.tsx
- src/stories/grid/GridPopoutEditGeneric.stories.tsx
- src/stories/grid/GridPopoutEditGenericTextArea.stories.tsx
- src/stories/grid/GridPopoverEditBearing.stories.tsx
- src/stories/grid/GridPopoverEditDropDown.stories.tsx
- src/stories/grid/GridPopoverEditMultiSelect.stories.tsx
- src/stories/grid/GridPopoverEditMultiSelectGrid.stories.tsx
- src/stories/grid/GridReadOnly.stories.tsx
- src/stories/grid/interactions/GridKeyboardInteractions.stories.tsx
- src/styles/GridTheme.scss
- src/utils/storybookTestUtil.ts
* Debounce redrawRows
* Fix cell selection padding
* Added waitForGridReady
> Fix selection cell styles, debounce redraw rows, add waitForGridReady

- src/components/gridPopoverEdit/GridPopoverMenu.tsx
- src/contexts/GridContextProvider.tsx
- src/utils/storybookTestUtil.ts
- src/utils/testUtil.ts
* Dont sort popovers 
* Add some table ready test utils
> Dont sort popovers and some test utils

- src/utils/testUtil.ts
Make waitForGrid props optional
> Make waitForGrid props optional

- src/utils/testUtil.ts
wait for grid row Timeout is optional
> wait for grid row Timeout is optional

- src/components/Grid.tsx
- src/contexts/GridContext.tsx
- src/contexts/GridContextProvider.tsx
* Fix autosizing flex columns, flex columns should not be initially ignored
> Fix autosizing flex columns

- package-lock.json
- package.json
> chore: fix ag-grid as v29

- src/components/gridForm/GridFormDropDown.tsx
Dont allow save whilst options are loading in GridFormDropdown
> Dont allow save whilst options are loading GridFormDropdown

- src/components/Grid.tsx
This PR fixes the following row drag issues:
* first row does not fire drag end event
* dragging a row to position it is already in should not fire the drag end event
Post merge …
> fix: row drag issues

- src/components/Grid.tsx
- src/stories/grid/GridDragRow.stories.tsx
- src/styles/Grid.scss
- src/styles/GridTheme.scss
Css interferes with grids that aren't using step-grid-theme
Wrapped these grid themes in a class.
> Move css into GridTheme

- src/utils/testUtil.ts
> fix: findRow was erroring if no pinned columns present

- src/components/Grid.tsx
- src/styles/GridTheme.scss
* Add single click edit global param on grid
* Add styles for borders.
> feat: Add single click edit

- src/styles/GridTheme.scss
Added drop shadow to pinned columns
Post merge
> fix: added drop shadow to pinned columns

- package-lock.json
- package.json
> Lui is now a peerDep

- src/components/Grid.tsx
- src/contexts/GridContext.tsx
- src/contexts/GridContextProvider.tsx
- src/stories/grid/GridReadOnly.stories.tsx
<Grid loading={true/false}/>
Adds spinner overlay if loading is true
> Add loading attribute

- src/components/gridForm/GridFormPopoverMenu.tsx
- src/stories/grid/GridReadOnly.stories.tsx
Support submenu in popup menu
```
{
label: "Sub menu...",
subMenu: () => <MenuItem>Find...</MenuItem>,
},
```
> Support submenu in popup menu

- src/components/Grid.tsx
add suppress cell selection feature
Post merge
> feat: suppress cell selection

- src/stories/grid/GridViewList.stories.tsx
- src/styles/GridTheme.scss
> feat: SURVEY-19184 to add new viewing list theme

- src/components/Grid.tsx
- src/components/GridNoRowsOverlay.tsx
- src/styles/GridTheme.scss
> feat: add no matching msg

- src/components/Grid.tsx
- src/stories/grid/GridPinnedRow.stories.tsx
- src/stories/grid/GridReadOnly.stories.tsx
- src/styles/Grid.scss
Jay would like to add pinned rows to the bottom of the table to allow users to add totals to the bottom of the table [SJ-918](https://toitutewhenua.atlassian.net/browse/SJ-918)
Post merge …
> feat: SJ-918 adding optional pinned rows to top and bottom of table

- src/utils/testUtil.ts
Array.from(rows.children) doesn't work
reverted to [...rows.children]
> FIX: broken test util

- src/components/Grid.tsx
- src/contexts/GridContextProvider.tsx
> FIX: NPE on getColumnState

- src/components/Grid.tsx
> FIX: autosize

- src/contexts/GridPopoverContext.tsx
- src/contexts/GridPopoverContextProvider.tsx
FEATURE: add colId to popover grid context
> FEATURE: add colId to popover grid context

- README.md
chromatic url that points to github is broken, changed to point to chromatic.
> fix: chromatic url

- src/components/Grid.tsx
See https://linz.slack.com/archives/C044T4WFFT4/p1724976207632129
Add a new optional parameter `defaultPostSort` to override post sort behavior (new item to last), default to `true`.
Post merge
**perf**: A code change that improves …
> feat: SRVTRI-3123 Add defaultPostSort option

- package-lock.json
- package.json
- src/lui/TextAreaInput.tsx
Replace uuid lib with React.useId
> fix: remove uuid library

- src/styles/Grid.scss
> fix: Fix cell centering

- src/components/gridPopoverEdit/GridButton.tsx
- src/components/gridPopoverEdit/index.ts
- src/stories/grid/GridPopoutEditBoolean.stories.tsx
- src/stories/grid/GridPopoverEditDropDown.stories.tsx
> feat: Grid button

- src/components/clickInputWhenContainingCellClicked.tsx
fix: loop when readonly is true
> fix: loop when readonly is true

- src/components/clickInputWhenContainingCellClicked.tsx
fix: loop on boolean edit when read only
> fix: loop on boolean edit when read only

- README.md
> feat: bump version

- src/styles/Grid.scss
> BREAKING CHANGE: deploy

- src/styles/GridTheme.scss
> fix: relative url in css

- src/components/Grid.tsx
> feat: Add hideSelectColumn

- src/components/GridCell.test.tsx
- src/components/GridCell.tsx
- src/components/gridPopoverEdit/GridButton.tsx
- src/react-menu3/components/ControlledMenu.tsx
BREAKING CHANGE: replace SA generics with aggrid standard
Remove all SA*** generic types and replace with ag-grid types.
BREAKING CHANGE: replace SA generics with aggrid standard
> BREAKING CHANGE: replace SA generics with aggrid standard

- src/components/Grid.tsx
- src/components/GridCell.tsx
- src/components/gridPopoverEdit/GridPopoverMenu.tsx
- src/components/gridPopoverEdit/GridPopoverMessage.ts
- src/components/gridRender/GridRenderGenericCell.tsx
- src/contexts/GridContext.tsx
- src/contexts/GridContextProvider.tsx
- src/stories/grid/GridPopoverEditDropDown.stories.tsx
Fixed single click edit and moved col setting to colDef from cellRendererProps.
> feat: single click edit moved from cell renderer params to col def

- src/components/gridForm/GridFormDropDown.tsx
- src/components/gridPopoverEdit/GridPopoverEditDropDown.ts
- src/react-menu3/components/ControlledMenu.tsx
- src/stories/grid/GridPopoverEditDropDown.stories.tsx
feat: Fix Option types in drop downs
Option types were the field type, but that is incorrect.  It _could_ be the field type, not _must_ be.
> feat: Fix Option types in drop downs

- src/contexts/GridContextProvider.tsx
> fix: handle gridApi.isDestroyed

- src/contexts/GridContextProvider.tsx
> fix: destroyed api error

- src/components/Grid.tsx
- src/components/GridCellFiller.tsx
- src/contexts/GridContextProvider.tsx
> fix: don't edit non editable cells

- src/components/Grid.tsx
- src/stories/grid/GridReadOnly.stories.tsx
feat: Add enableClickSelection,enableSelectionWithoutKeys
> feat: Add enableClickSelection,enableSelectionWithoutKeys

- src/utils/__tests__/testUtil.ts
- src/utils/__tests__/vitestUtil.ts
> chore: add clickColumnHeaderToSort action

- src/utils/__tests__/testUtil.ts
- src/utils/__tests__/vitestUtil.ts
fix: missing test utils for menus
> fix: missing test utils

- src/react-menu3/components/ControlledMenu.tsx
- src/stories/grid/gridFormInteraction/GridFormDropDownInteraction.stories.tsx
- src/stories/grid/gridFormInteraction/GridFormPopoverMenuInteraction.stories.tsx
> fix: remove debug logs

- src/utils/__tests__/testUtil.ts
- src/utils/__tests__/vitestUtil.ts
> fix: increase timeouts

- .eslintrc.cjs
- src/utils/__tests__/testUtil.ts
- tsconfig.json
> fix:longer wait for popover

- src/utils/__tests__/testUtil.ts
- src/utils/__tests__/vitestUtil.ts
Row counter did not take pinned rows into account (i.e. exclude them)
> fix: test util row counter

- src/components/GridPopoverHook.tsx
- src/contexts/GridContextProvider.tsx
- src/index.ts
- src/stories/grid/gridFormInteraction/GridFormDropDownInteraction.stories.tsx
- src/stories/grid/gridFormInteraction/GridFormEditBearingCorrectionInteraction.stories.tsx
- src/stories/grid/gridFormInteraction/GridFormEditBearingInteraction.stories.tsx
- src/stories/grid/gridFormInteraction/GridFormMultiSelectGridInteraction.stories.tsx
- src/stories/grid/gridFormInteraction/GridFormMultiSelectInteraction.stories.tsx
- src/stories/grid/gridFormInteraction/GridFormPopoverMenuInteraction.stories.tsx
- src/stories/grid/gridFormInteraction/GridFormTextAreaInteraction.stories.tsx
- src/stories/grid/gridFormInteraction/GridFormTextInputInteraction.stories.tsx
- src/utils/waitForCondition.tsx
Cells are partially updating without redrawRows being called after edit
> fix: redraw rows after edit

- src/components/Grid.tsx
- src/components/GridCell.tsx
- src/components/GridPopoverHook.tsx
- src/components/gridForm/GridFormDropDown.tsx
- src/components/gridForm/GridFormMultiSelect.tsx
- src/components/gridPopoverEdit/GridPopoverMessage.ts
- src/contexts/GridContext.tsx
- src/contexts/GridContextProvider.tsx
- src/stories/grid/GridPopoutEditGeneric.stories.tsx
- src/stories/grid/GridPopoverEditMultiSelect.stories.tsx
- src/stories/grid/GridPopoverEditMultiSelectGrid.stories.tsx
- src/stories/grid/gridFormInteraction/GridFormDropDownInteraction.stories.tsx
- src/stories/grid/gridFormInteraction/GridFormEditBearingCorrectionInteraction.stories.tsx
- src/stories/grid/gridFormInteraction/GridFormEditBearingInteraction.stories.tsx
- src/stories/grid/gridFormInteraction/GridFormMultiSelectInteraction.stories.tsx
- src/stories/grid/gridFormInteraction/GridFormPopoverMenuInteraction.stories.tsx
- src/stories/grid/gridFormInteraction/GridFormTextAreaInteraction.stories.tsx
- src/stories/grid/gridFormInteraction/GridFormTextInputInteraction.stories.tsx
- src/stories/grid/interactions/GridKeyboardInteractions.stories.tsx
- src/utils/waitForCondition.tsx
fix: use refresh cells not redraw rows
> fix: use refresh cells not redraw rows

- src/components/GridPopoverHook.tsx
- src/components/gridForm/GridFormDropDown.tsx
- src/stories/grid/gridFormInteraction/GridFormEditBearingCorrectionInteraction.stories.tsx
Sometimes drop downs fail to be clickable.
Attempting to fix.
> fix: dropdown async load
